### ISSUE TITLE
cannot compile, it doesn't find the include file on MT5

### ISSUE THREAD

**Issue by BarbzYHOOL** [EarnForex/RiskCalculator#1]
cannot compile, it doesn't find the include file

**Comment by BarbzYHOOL** [comment]
There is no real instruction, only the generic ones

I've put the whole directory inside MQL5/Indicators/ and it doesn't work

I've already compiled successfully another EA from earnforex so wtf

**Comment by BarbzYHOOL** [comment]
Ok i fixed it myself, never touched any MQL in my life but eh...

I dunno why, as I'm not a C dev, but I changed from 
#include <DOMObject.mqh>
To:
#include "DOMObject.mqh";


dunno what you did here but it seems like basic stuff lol, I also moved all files and fixed the icon path


PS: even though it compiled, this one PLUS position_sizer expert no longer load !!!!
![image](https://github.com/EarnForex/RiskCalculator/assets/29780637/c72a9ba3-20ed-4420-b19a-29f6f3774e7f)

**Comment by EarnForex** [comment]
The .mqh files that come with Risk Calculator should be copied to the Include folder of the MQL5 subfolder - the same as in the downloaded directory structure.
